trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - develop
      - release*
  paths:
    exclude:
      - README.md

variables:
  repository: 'focal-freedom-236620/operator'
  build: $(Build.BuildId)
  ref: $(Build.SourceBranch)
  version:

jobs:
  - job: Operator
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
    - script: |
          if [[ $(ref) == refs/tags* ]]; then
            TAG=$(echo $(ref) | sed "s|refs/tags/v||g")
            echo "##vso[task.setvariable variable=version]$TAG"
          else
            LATESTTAG=$(git tag | tail -1)
            LATESTVERS=${LATESTTAG#?}
            if [ -z "$LATESTVERS" ]; then LATESTVERS=0.0.0; fi
            echo "##vso[task.setvariable variable=version]$LATESTVERS-b$(build)"
          fi
          echo $(version)
      displayName: 'Set version variable'

    - task: Docker@2
      displayName: 'build docker'
      inputs:
        containerRegistry: 'Edgeworx GCP'
        repository: $(repository)
        command: 'buildAndPush'
        Dockerfile: 'build/Dockerfile'
        buildContext: './'
        tags: |
          $(version)
          latest