apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    createdAt: "2024-11-08T10:47:12Z"
    operators.operatorframework.io/builder: operator-sdk-v1.37.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: iofog-operator.v3.4.7
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - kind: Application
        name: apps.datasance.com
        version: v3
      - kind: ControlPlane
        name: controlplanes.datasance.com
        version: v3
  description: ioFog Control Plane on Kubernetes
  displayName: iofog-operator
  icon:
    - base64data: ""
      mediatype: ""
  install:
    spec:
      deployments:
        - label:
            name: iofog-operator
          name: iofog-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: iofog-operator
            strategy: {}
            template:
              metadata:
                labels:
                  name: iofog-operator
              spec:
                containers:
                  - args:
                      - --enable-leader-election
                    command:
                      - iofog-operator
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.annotations['olm.targetNamespaces']
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: iofog-operator
                    image: ghcr.io/datasance/operator@sha256:93b46cf8a9877dba64172e6493b0768e45b2192e66d38e1a1d1acd9eb60bbbe6
                    imagePullPolicy: Always
                    name: iofog-operator
                    resources: {}
                serviceAccountName: iofog-operator
                terminationGracePeriodSeconds: 10
      permissions:
        - rules:
            - apiGroups:
                - coordination.k8s.io
              resources:
                - leases
              verbs:
                - '*'
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - roles
                - rolebindings
              verbs:
                - '*'
            - apiGroups:
                - networking.k8s.io
              resources:
                - ingresses
                - ingresses/status
              verbs:
                - '*'
            - apiGroups:
                - datasance.com
              resources:
                - applications
                - apps
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - datasance.com
              resources:
                - applications/status
                - apps/finalizers
                - applications/finalizers
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - datasance.com
              resources:
                - controlplanes
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - datasance.com
              resources:
                - controlplanes/status
                - controlplanes/finalizers
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - apps
              resources:
                - deployments
              verbs:
                - '*'
            - apiGroups:
                - ""
              resources:
                - pods
                - configmaps
                - configmaps/status
                - events
                - serviceaccounts
                - services
                - persistentvolumeclaims
                - secrets
              verbs:
                - '*'
          serviceAccountName: iofog-operator
    strategy: deployment
  installModes:
    - supported: false
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - iofog
    - datasance
    - pot
  links:
    - name: Datasance PoT // Iofog Operator
      url: https://datasance.com
  maturity: stable
  minKubeVersion: 1.18.0
  provider:
    name: Datasance
  relatedImages:
    - image: ghcr.io/datasance/operator:latest
      name: iofog-operator
  version: 3.4.7
