apiVersion: iokog.iofog.org/v1alpha1
kind: Kog
metadata:
  name: example-kog
spec:
  iofogUser:
    name: Serge
    surname: Radinovich
    email: serge@edgeworx.io
    password: Operator456EW123
  controllerCount: 1
  connectorCount: 1
  controllerImage: ""
  operatorImage: ""
  connectorImage: ""
  kubeletImage: ""
  database:
   provider: "" 
   host: ""
   port: 0
   user: ""
   password: ""
   databaseName: ""


