apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kogs.iokog.iofog.org
spec:
  group: iokog.iofog.org
  names:
    kind: Kog
    listKind: KogList
    plural: kogs
    singular: kog
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            connectorCount:
              format: int64
              type: integer
            connectorImage:
              type: string
            controllerCount:
              format: int64
              type: integer
            controllerImage:
              type: string
            database:
              properties:
                databaseName:
                  type: string
                host:
                  type: string
                password:
                  type: string
                port:
                  format: int64
                  type: integer
                provider:
                  type: string
                user:
                  type: string
              required:
              - provider
              - host
              - port
              - user
              - password
              - databaseName
              type: object
            iofogUser:
              properties:
                email:
                  type: string
                name:
                  type: string
                password:
                  type: string
                surname:
                  type: string
              required:
              - name
              - surname
              - email
              - password
              type: object
            kubeletImage:
              type: string
          required:
          - iofogUser
          - controllerCount
          - connectorCount
          type: object
        status:
          properties:
            connectorCount:
              format: int64
              type: integer
            connectorPods:
              items:
                type: string
              type: array
            controllerCount:
              format: int64
              type: integer
            controllerPods:
              items:
                type: string
              type: array
          required:
          - controllerPods
          - connectorPods
          - controllerCount
          - connectorCount
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
