apiVersion: k8s.iofog.org/v1alpha2
kind: ControlPlane
metadata:
  name: example-controlplane
spec:
  controllerReplicaCount: 1
  controllerImage: ""
  database:
    provider: ""
    host: ""
    port: 0
    user: ""
    password: ""
    databaseName: ""
