apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kogs.k8s.iofog.org
spec:
  group: k8s.iofog.org
  names:
    kind: Kog
    listKind: KogList
    plural: kogs
    singular: kog
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
