apiVersion: iofog.org/v2
kind: ControlPlane
metadata:
  name: iokog
  namespace: default
spec:
  controlPlane:
    user:
      name: "Serge
      surname: "Radinovich"
      email: "serge@edgeworx.io"
      password: "FDJLhu98buisdkj"
    database:
      provider: ""
      host: ""
      port: 0
      user: ""
      password: ""
      databaseName: ""
    services:
      controller:
        type: ""
        address: ""
      router:
        type: ""
        address: ""
      proxy:
        type: ""
        address: ""
    replicas:
      controller: 0
    images:
      pullSecret: ""
      kubelet: ""
      controller: ""
      router: ""
      portManager: ""
      proxy: ""
    ingresses:
      router:
        address: ""
        httpPort: 0
        messagePort: 0
        interiorPort: 0
        edgePort: 0
      httpProxy:
        address: ""
      tcpProxy:
        address: ""
        tcpAllocatorPort: 0
        tcpAllocatorHost: ""
        ecnId: 0
