apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kogs.iofog.org
spec:
  group: iofog.org
  names:
    kind: Kog
    listKind: KogList
    plural: kogs
    singular: kog
  scope: Namespaced
  subresources:
    status: {}
  version: v2
  versions:
  - name: v2
    served: true
    storage: true
