apiVersion: v1
kind: ServiceAccount
metadata:
  name: iofog-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: iofog-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - namespaces
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - k8s.iofog.org
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
    - iokog.iofog.org
    resources:
    - '*'
    verbs:
    - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: iofog-operator
subjects:
  - kind: ServiceAccount
    name: iofog-operator
roleRef:
  kind: Role
  name: iofog-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iofog-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: iofog-operator
  template:
    metadata:
      labels:
        name: iofog-operator
    spec:
      serviceAccountName: iofog-operator
      containers:
        - name: iofog-operator
          image: gcr.io/focal-freedom-236620/operator:serge
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - iofog-operator
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "iofog-operator"
